# Generated by Django 5.2.1 on 2025-06-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='price_at_transaction',
            new_name='transaction_price',
        ),
    ]
